name: Competitor AI Agent

on:
  schedule:
    - cron: '0 8 * * 1' 
  workflow_dispatch: 

jobs:
  investigate:
    runs-on: ubuntu-latest
    steps:
      - name: Grab my files
        uses: actions/checkout@v5  # Updated from v4

      - name: Install Python
        uses: actions/setup-python@v6 # Updated from v5
        with:
          python-version: '3.11'

      - name: Install tool kits
        run: pip install requests google-genai
        
      - name: Run the Agent
        env:
          SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Save the final report
        uses: actions/upload-artifact@v4
        with:
          name: Intelligence-Report
          path: report.md
